#!/usr/bin/env bash
set -euo pipefail

# submit-package.sh — packages a CS3704 submission for Canvas (package method).
# Produces a session summary, copies session artifacts, and zips the package
# into cs3704-submission-<timestamp>.zip at the project root.
#
# Usage: .opencode/scripts/submit-package.sh [extra files/dirs to include...]

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
SUBMIT_DIR="cs3704-submission-$TIMESTAMP"
ZIP="$ROOT/cs3704-submission-$TIMESTAMP.zip"

# 1. Session summary (create a stub if the student hasn't written one)
#    Ensure a timestamped entry is present for this session (agents handle it automatically)
#    This adds a heading with the current UTC timestamp so the summary grows across sessions without student action.
#    If an entry for the exact timestamp already exists, it is not duplicated.
#    The placeholder line can be edited later by the student if desired.
if [ ! -f session-summary.md ]; then
  printf '# Session Summary\n\nGenerated by submit-package.sh — edit to describe the work submitted.\n' > session-summary.md
fi

# 2. Assemble package contents
rm -rf "$SUBMIT_DIR"
mkdir -p "$SUBMIT_DIR"
cp session-summary.md "$SUBMIT_DIR/"
# Also copy any per‑session summary files if they exist
cp session-summary-*.md "$SUBMIT_DIR/" 2>/dev/null || true

# Session transcripts, if any
cp session-*.json session-*.md "$SUBMIT_DIR/" 2>/dev/null || true

# AI disclosure file (mandatory for link submissions, included for package)
if [ -f ai_disclosure.md ]; then
  cp ai_disclosure.md "$SUBMIT_DIR/"
fi

# Extra files/dirs passed as arguments
for item in "$@"; do
  if [ -e "$item" ]; then
    cp -r "$item" "$SUBMIT_DIR/"
  else
    echo "Warning: '$item' not found; skipping." >&2
  fi
  done

# Automatically add a timestamped heading for this session if not already present
CURRENT_UTC="$(date -u +%Y%m%d-%H%M%S)"
HEADING="## Session $CURRENT_UTC (UTC)"
if ! grep -q "^${HEADING}$" session-summary.md; then
  printf "\n${HEADING}\n\n- (auto‑generated entry – edit to describe this session)\n" >> session-summary.md
fi

# 3. Package it
if command -v zip >/dev/null 2>&1; then
  (cd "$ROOT" && zip -rq "$ZIP" "$SUBMIT_DIR")
else
  tar -czf "$ZIP" -C "$ROOT" "$SUBMIT_DIR"   # fallback if zip is unavailable
fi

echo "Submission package created: $ZIP"
